# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/taoyao/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),taoyao)

$(call add-radio-file-sha1-checked,radio/abl.img,9465b02c99e1543521a4dad6623540bc48026100)
$(call add-radio-file-sha1-checked,radio/aop.img,c2a868c027ed9d1b96370054e953c589fdbd59f1)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,59318f2d543b20c1a93517743aef50e2c55e0ce4)
$(call add-radio-file-sha1-checked,radio/cpucp.img,85537275a5ce175fedc3790f0f8ee2d8de3e8fae)
$(call add-radio-file-sha1-checked,radio/devcfg.img,ce0acd2532a2d2ad876b59ab15d3f5711ab87b3e)
$(call add-radio-file-sha1-checked,radio/dsp.img,c21e6e8bf124b76385a8f00c14baf084e9623352)
$(call add-radio-file-sha1-checked,radio/featenabler.img,8385e6943cf2e499b147bef19791044b460e3a0c)
$(call add-radio-file-sha1-checked,radio/hyp.img,f1ddaed882012fce72bbc85359623da9b0bfbf52)
$(call add-radio-file-sha1-checked,radio/imagefv.img,aa7b70c7eeb73620ebbd9ed03ffc38a1e379ca2b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,adf628201bee7a42e4ebddf223e55bb66379b15b)
$(call add-radio-file-sha1-checked,radio/modem.img,3d8267463b7d5a9d7ae4b04e5ccf1c244b6913b5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,fbcec76360cb6210f6e62ab5a91e4c060c1dbd80)
$(call add-radio-file-sha1-checked,radio/shrm.img,e43e80f3efb9d078c4735d531da8e60f990ad1b9)
$(call add-radio-file-sha1-checked,radio/tz.img,78215a2436c4a1c71599e7a6efe180652ce5d2db)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,3b5d628bd5bfed01e523c1a0c94905911ecbadbf)
$(call add-radio-file-sha1-checked,radio/xbl.img,6d449c09dc28d05039368e4f23e49d438824da20)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,6a0636171a537c1e5d313338fe5821f269fbcec2)

endif
